/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedVirtualScenesIndexRouteImport } from './routes/_authenticated/virtual-scenes/index'
import { Route as AuthenticatedViewsIndexRouteImport } from './routes/_authenticated/views/index'
import { Route as AuthenticatedUtilityPremisesIndexRouteImport } from './routes/_authenticated/utility-premises/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTypicalLayoutsIndexRouteImport } from './routes/_authenticated/typical-layouts/index'
import { Route as AuthenticatedRegionLinksIndexRouteImport } from './routes/_authenticated/region-links/index'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './routes/_authenticated/permissions/index'
import { Route as AuthenticatedOverviewsIndexRouteImport } from './routes/_authenticated/overviews/index'
import { Route as AuthenticatedOtherInfoIndexRouteImport } from './routes/_authenticated/other-info/index'
import { Route as AuthenticatedFloorPlanIndexRouteImport } from './routes/_authenticated/floor-plan/index'
import { Route as AuthenticatedApartmentInteriorsIndexRouteImport } from './routes/_authenticated/apartment-interiors/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVirtualScenesIndexRoute =
  AuthenticatedVirtualScenesIndexRouteImport.update({
    id: '/virtual-scenes/',
    path: '/virtual-scenes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedViewsIndexRoute = AuthenticatedViewsIndexRouteImport.update({
  id: '/views/',
  path: '/views/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUtilityPremisesIndexRoute =
  AuthenticatedUtilityPremisesIndexRouteImport.update({
    id: '/utility-premises/',
    path: '/utility-premises/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTypicalLayoutsIndexRoute =
  AuthenticatedTypicalLayoutsIndexRouteImport.update({
    id: '/typical-layouts/',
    path: '/typical-layouts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegionLinksIndexRoute =
  AuthenticatedRegionLinksIndexRouteImport.update({
    id: '/region-links/',
    path: '/region-links/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverviewsIndexRoute =
  AuthenticatedOverviewsIndexRouteImport.update({
    id: '/overviews/',
    path: '/overviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOtherInfoIndexRoute =
  AuthenticatedOtherInfoIndexRouteImport.update({
    id: '/other-info/',
    path: '/other-info/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFloorPlanIndexRoute =
  AuthenticatedFloorPlanIndexRouteImport.update({
    id: '/floor-plan/',
    path: '/floor-plan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApartmentInteriorsIndexRoute =
  AuthenticatedApartmentInteriorsIndexRouteImport.update({
    id: '/apartment-interiors/',
    path: '/apartment-interiors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/apartment-interiors/': typeof AuthenticatedApartmentInteriorsIndexRoute
  '/floor-plan/': typeof AuthenticatedFloorPlanIndexRoute
  '/other-info/': typeof AuthenticatedOtherInfoIndexRoute
  '/overviews/': typeof AuthenticatedOverviewsIndexRoute
  '/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/region-links/': typeof AuthenticatedRegionLinksIndexRoute
  '/typical-layouts/': typeof AuthenticatedTypicalLayoutsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/utility-premises/': typeof AuthenticatedUtilityPremisesIndexRoute
  '/views/': typeof AuthenticatedViewsIndexRoute
  '/virtual-scenes/': typeof AuthenticatedVirtualScenesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/apartment-interiors': typeof AuthenticatedApartmentInteriorsIndexRoute
  '/floor-plan': typeof AuthenticatedFloorPlanIndexRoute
  '/other-info': typeof AuthenticatedOtherInfoIndexRoute
  '/overviews': typeof AuthenticatedOverviewsIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/region-links': typeof AuthenticatedRegionLinksIndexRoute
  '/typical-layouts': typeof AuthenticatedTypicalLayoutsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/utility-premises': typeof AuthenticatedUtilityPremisesIndexRoute
  '/views': typeof AuthenticatedViewsIndexRoute
  '/virtual-scenes': typeof AuthenticatedVirtualScenesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/apartment-interiors/': typeof AuthenticatedApartmentInteriorsIndexRoute
  '/_authenticated/floor-plan/': typeof AuthenticatedFloorPlanIndexRoute
  '/_authenticated/other-info/': typeof AuthenticatedOtherInfoIndexRoute
  '/_authenticated/overviews/': typeof AuthenticatedOverviewsIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/region-links/': typeof AuthenticatedRegionLinksIndexRoute
  '/_authenticated/typical-layouts/': typeof AuthenticatedTypicalLayoutsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/utility-premises/': typeof AuthenticatedUtilityPremisesIndexRoute
  '/_authenticated/views/': typeof AuthenticatedViewsIndexRoute
  '/_authenticated/virtual-scenes/': typeof AuthenticatedVirtualScenesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/apartment-interiors/'
    | '/floor-plan/'
    | '/other-info/'
    | '/overviews/'
    | '/permissions/'
    | '/region-links/'
    | '/typical-layouts/'
    | '/users/'
    | '/utility-premises/'
    | '/views/'
    | '/virtual-scenes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/apartment-interiors'
    | '/floor-plan'
    | '/other-info'
    | '/overviews'
    | '/permissions'
    | '/region-links'
    | '/typical-layouts'
    | '/users'
    | '/utility-premises'
    | '/views'
    | '/virtual-scenes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/apartment-interiors/'
    | '/_authenticated/floor-plan/'
    | '/_authenticated/other-info/'
    | '/_authenticated/overviews/'
    | '/_authenticated/permissions/'
    | '/_authenticated/region-links/'
    | '/_authenticated/typical-layouts/'
    | '/_authenticated/users/'
    | '/_authenticated/utility-premises/'
    | '/_authenticated/views/'
    | '/_authenticated/virtual-scenes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/virtual-scenes/': {
      id: '/_authenticated/virtual-scenes/'
      path: '/virtual-scenes'
      fullPath: '/virtual-scenes/'
      preLoaderRoute: typeof AuthenticatedVirtualScenesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/views/': {
      id: '/_authenticated/views/'
      path: '/views'
      fullPath: '/views/'
      preLoaderRoute: typeof AuthenticatedViewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/utility-premises/': {
      id: '/_authenticated/utility-premises/'
      path: '/utility-premises'
      fullPath: '/utility-premises/'
      preLoaderRoute: typeof AuthenticatedUtilityPremisesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/typical-layouts/': {
      id: '/_authenticated/typical-layouts/'
      path: '/typical-layouts'
      fullPath: '/typical-layouts/'
      preLoaderRoute: typeof AuthenticatedTypicalLayoutsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/region-links/': {
      id: '/_authenticated/region-links/'
      path: '/region-links'
      fullPath: '/region-links/'
      preLoaderRoute: typeof AuthenticatedRegionLinksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overviews/': {
      id: '/_authenticated/overviews/'
      path: '/overviews'
      fullPath: '/overviews/'
      preLoaderRoute: typeof AuthenticatedOverviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/other-info/': {
      id: '/_authenticated/other-info/'
      path: '/other-info'
      fullPath: '/other-info/'
      preLoaderRoute: typeof AuthenticatedOtherInfoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/floor-plan/': {
      id: '/_authenticated/floor-plan/'
      path: '/floor-plan'
      fullPath: '/floor-plan/'
      preLoaderRoute: typeof AuthenticatedFloorPlanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apartment-interiors/': {
      id: '/_authenticated/apartment-interiors/'
      path: '/apartment-interiors'
      fullPath: '/apartment-interiors/'
      preLoaderRoute: typeof AuthenticatedApartmentInteriorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApartmentInteriorsIndexRoute: typeof AuthenticatedApartmentInteriorsIndexRoute
  AuthenticatedFloorPlanIndexRoute: typeof AuthenticatedFloorPlanIndexRoute
  AuthenticatedOtherInfoIndexRoute: typeof AuthenticatedOtherInfoIndexRoute
  AuthenticatedOverviewsIndexRoute: typeof AuthenticatedOverviewsIndexRoute
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
  AuthenticatedRegionLinksIndexRoute: typeof AuthenticatedRegionLinksIndexRoute
  AuthenticatedTypicalLayoutsIndexRoute: typeof AuthenticatedTypicalLayoutsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedUtilityPremisesIndexRoute: typeof AuthenticatedUtilityPremisesIndexRoute
  AuthenticatedViewsIndexRoute: typeof AuthenticatedViewsIndexRoute
  AuthenticatedVirtualScenesIndexRoute: typeof AuthenticatedVirtualScenesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApartmentInteriorsIndexRoute:
    AuthenticatedApartmentInteriorsIndexRoute,
  AuthenticatedFloorPlanIndexRoute: AuthenticatedFloorPlanIndexRoute,
  AuthenticatedOtherInfoIndexRoute: AuthenticatedOtherInfoIndexRoute,
  AuthenticatedOverviewsIndexRoute: AuthenticatedOverviewsIndexRoute,
  AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
  AuthenticatedRegionLinksIndexRoute: AuthenticatedRegionLinksIndexRoute,
  AuthenticatedTypicalLayoutsIndexRoute: AuthenticatedTypicalLayoutsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedUtilityPremisesIndexRoute:
    AuthenticatedUtilityPremisesIndexRoute,
  AuthenticatedViewsIndexRoute: AuthenticatedViewsIndexRoute,
  AuthenticatedVirtualScenesIndexRoute: AuthenticatedVirtualScenesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
